name: 'PR AI Code Commenter Action'
description: 'Perform code reviews and comment on diffs using OpenAI API.'
author: 'David Santana Cabrera'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'aperture'
  color: 'green'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
